esp32c2 support (IDF v5.2.2)
micropython/micropython pull request #15906
Opened 2024-09-24 18:54 UTC by TrekMax

### Summary

The is esp32c2 officially supported in IDF v5.2 but requires a number of changes to work...
Pulling together changes and generic board support needed here.

### Testing

Functions verified by actual hardware include:
- machine.pin
- machine.i2c
- machine.adc
- machine.pwm
- machine.timer
- bluetooth

2024-09-24 21:18 UTC, sanderjo commented
> Isn't this already covered by #11869?

That is about esp32c6

This PR has subject esp32c2.

So c6 versus c2?

2024-09-24 21:24 UTC, andrewleech commented
Nice one @sanderjo there's a bunch of new chips getting added to IDF these days! 

It still needs testing but this commit on the top of my C6 branch is intended to make it easier to bring in new chips like this one if you want to take a look: https://github.com/micropython/micropython/pull/15862

2024-09-24 21:34 UTC, agatti commented
@sanderjo I saw the ESP32C2 definition in `mpconfigport.h` in @andrewleech's branch so I thought it had basic C2 integration too, along with IDF 5.2 - my bad.

2024-09-24 21:37 UTC, agatti commented
@TrekMax `MICROPY_EMIT_RV32` being enabled should work on ESP32C2 too, it has the same RV32 core as C3 after all.  Same for `MICROPY_NLR_SETJMP` being disabled.

2024-09-24 22:24 UTC, andrewleech commented
@agatti the latest changes on C6 (about to push) should enable the emitter on all risk chips based on the soc defines, rather than listing individual chips. 

I suggest this PR would be well placed to rebase on top of the C6 work once it's merged as lots of people have contributed to that PR to help it fill gaps / support that will then naturally apply to many of the newer chips.

2024-09-24 22:36 UTC, agatti commented
@andrewleech oh, that's nice to hear.  Hopefully that would make support for the C5 easier to add once that chip shows up in production :)

2024-09-25 04:34 UTC, projectgus commented
Thanks @TrekMax for updating your PR! (Note for housekeeping: this is replacing earlier PR #15440).

Similar to discussions above, suggest we tackle in this order:

1. Merge #11869 
2. Damien will do the upcoming 1.24 MicroPython release.
3. Merge #15862 - this should make adding future SoCs much simpler, but has some risk of bugs in other SoCs.
4. Rebase this branch, then review and merge ESP32-C2 support.

@TrekMax Let us know if we can help with any part of this process. It should be possible to update this PR with totally new commits without needing to close and open a new PR. There is a guide to doing this online at https://github.com/jimmo/git-and-micropython#README

2024-09-27 03:38 UTC, TrekMax commented
Thanks. I will wait for esp32c6 support (IDF v5.2) #11869 to be merged, then rebase this branch, and then review and commit ESP32-C2 support.

2024-10-14 13:41 UTC, TrekMax commented
@projectgus Hey , the commit has been rebased to the latest master, please review it. Thanks!

2024-10-14 14:27 UTC, andrewleech commented
Hi @TrekMax could you also take a look at this which is intended to make it much easier to bring in new chips: https://github.com/micropython/micropython/pull/15862

2024-10-16 01:57 UTC, TrekMax commented
@andrewleech Of course. I have ESP32C3, ESP32C2 and ESP32S3 to verify it.

2024-12-10 12:58 UTC, dpgeorge commented
@TrekMax please can you rebase this PR on the latest master, because there have been a lot of changes to the esp32 port, in particular support for IDF v5.3.

2024-12-10 22:29 UTC, projectgus commented
@TrekMax Further to damien's request: now that #15862 is merged a lot of the C2 specific #ifdefs are probably not needed, so the PR will hopefully become very simple. :grin:

2024-12-17 01:45 UTC, projectgus requested changes
Thanks for your patience and for the quick update of this PR, @TrekMax ! I have some comments below, mostly minor.

2024-12-17 01:45 UTC, projectgus commented on ports/esp32/mpconfigport.h
> +#define MICROPY_GC_INITIAL_HEAP_SIZE        (40 * 1024)
Just curious, is there a reason not to choose 36KB, same as ESP32-S2?

2024-12-17 01:45 UTC, projectgus commented on ports/esp32/machine_bitstream.c
> +    #if CONFIG_SOC_RMT_SUPPORTED
```suggestion
    #if SOC_RMT_SUPPORTED
```

2024-12-17 01:45 UTC, projectgus commented on ports/esp32/modesp32.c
> +    #if CONFIG_SOC_RMT_SUPPORTED
```suggestion
    #if SOC_RMT_SUPPORTED
```

2024-12-17 01:45 UTC, projectgus commented on ports/esp32/machine_bitstream.c
> +#if CONFIG_SOC_RMT_SUPPORTED
```suggestion
#if SOC_RMT_SUPPORTED
```

(This is a nitpick, but the only reason the `CONFIG_` prefix copy exists is for KConfig.)

2024-12-17 01:45 UTC, projectgus commented on ports/esp32/esp32_rmt.c
> +#define RMT_LAST_TX_CHANNEL (-1)
Instead of defining this macro to a dummy value, is it possible to put `#if SOC_RMT_SUPPORTED` around the entire C file so it's not compiled on C2?

2024-12-17 01:45 UTC, projectgus commented on ports/esp32/boards/sdkconfig.ble
> +CONFIG_BT_NIMBLE_TASK_STACK_SIZE=4096
This change probably should go in a chip-specific `sdkconfig.c2`, unless we're very sure all SoCs can run with the smaller stack size?

(The git log shows it had to be increased in cd66aa05c so there is some risk of regression if we make it smaller on all chips.)

2024-12-17 01:45 UTC, projectgus commented on ports/esp32/boards/ESP32_GENERIC_C2/mpconfigboard.cmake
> +    boards/sdkconfig.26mhz
Do all ESP32-C2 modules use 26MHz crystals? I see the docs say it can support both 26MHz and 40MHz.

2024-12-17 04:40 UTC, TrekMax commented on ports/esp32/boards/ESP32_GENERIC_C2/board.md
> +that use the revision 3 silicon (or newer).
Yes, This copy-paste from ESP32-C3, I will modify it. ESP32C2

2024-12-17 04:40 UTC, TrekMax commented on ports/esp32/.gitignore
> +.cache/
okays!

2025-01-17 04:55 UTC, projectgus commented on ports/esp32/boards/ESP32_GENERIC_C2/mpconfigboard.cmake
> +    boards/sdkconfig.26mhz
I see you moved this into the `sdkconfig.c2` file, which is fine.

Do we need to add a comment in `board.md` that is supports boards with 26MHz crystals? Or do the modules all have 26MHz crystals, already?

2025-01-17 04:56 UTC, projectgus commented
@TrekMax Thanks for updating the PR in response to the review! It's looking pretty tidy.

There are a couple of unresolved questions above, do you know the answer to them?

2025-01-17 04:58 UTC, projectgus commented on ports/esp32/boards/deploy_c2.md
> +Program your board using the esptool.py program, found [here](https://github.com/espressif/esptool).
A reminder for the future that #16535 deletes these copy-paste deploy.md files, so depending on which PR merges first there is a cleanup step for the PR which is merged second.

2025-01-17 06:24 UTC, projectgus commented on ports/esp32/boards/deploy_c2.md
> +Program your board using the esptool.py program, found [here](https://github.com/espressif/esptool).
The linked PR just merged, so it's OK to rebase this, remove this file, and link to the generic `deploy.md` now.

2025-03-07 12:33 UTC, AmirHmZz commented
@TrekMax Any updates on this PR?

2025-07-23 08:08 UTC, projectgus commented on ports/esp32/boards/ESP32_GENERIC_C2/mpconfigboard.cmake
> +    boards/sdkconfig.26mhz
Looks like all current "ESP32-C2 series" chips are ESP8684 and all ESP8684 modules use 26MHz crystals for compatibility with ESP8266.

Have added the crystal frequency to board.md in case someone gets one which uses 40MHz.

2025-07-23 08:13 UTC, projectgus commented
I've rebased this PR on master and done a number of tests. 

Good news: basic unit tests pass, peripheral unit tests pass.

Bad news: Wi-Fi is almost unusable, Bluetooth appears totally unusable.

* The `multi_net/` tests fail intermittently for non-TLS tests (timeouts, packet loss) and always fail for TLS tests. (ESP32-C3 passes these tests 100%).
* The `multi_inet/` tests mostly fail with ENOMEM for TLS. I tried tuning the heap size to get the `test_tls_sites_simple.py` to make a single TLS connection but could not (with 16KB Python heap the test fails with ENOMEM, with 12KB Python heap the test fails with MemoryError - i.e. there's either not enough ESP-IDF RAM or not enough Python RAM).
* The multi_bluetooth tests hard fault during initialisation (crash is in nimble_port, looks like the NimBLE host event queue is uninitialised.) Unsure what the root cause for this one is.

I think more work is needed for ESP32-C2 to be a supported MicroPython target. It has only 272KB of RAM vs 400KB for ESP32-C3, but we may be able to tune some ESP-IDF parameters to free up more RAM at runtime.

2025-07-23 08:14 UTC, projectgus commented
@dpgeorge Recommend we retarget this PR for 1.27 unless there's some miracle fix for the Wi-Fi & Bluetooth problems. :crying_cat_face: 

EDIT: Miracle fix may be possible, it turns out!

2025-07-25 04:55 UTC, projectgus commented
> miracle fix for the Wi-Fi & Bluetooth problems

Turns out this was possible! By tweaking various config settings it was possible to free up 40KB of static RAM (went from 60KB free static RAM to 100KB) and also reduce the runtime memory usage from Wi-Fi and TCP/IP. These tweaks are added in their own `sdkconfig.free_ram` file, as they're potentially useful for other chips as well.

With the free RAM increases implemented, tests pass:

* multi_net - passing [*][^]
* net_inet - passing
* multi_bluetooth - passing [*]
* unit tests - defaults, extmod_hardware & ports/esp32 - passing

[*] I had to tweak the run-multitests.py script for ESP32C2 as (like ESP8266) the ESP8684 prints its early boot log at 74880bps which is interpreted as line noise by the script and can trigger encoding errors. Will submit another PR for this.

[^] Except DTLS tests, it seems DTLS support has been disabled on ESP-IDF v5.4.2 (on all targets). Will investigate and submit a fix separately.

2025-07-28 12:00 UTC, dpgeorge commented on ports/esp32/boards/ESP32_GENERIC_C2/mpconfigboard.h
> +#define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "esp32c2"
I feel like this should go in `mpconfigport.h` with all the other ones.

2025-07-28 12:00 UTC, dpgeorge commented on ports/esp32/boards/ESP32_GENERIC_C2/mpconfigboard.h
> +#define MICROPY_HW_ENABLE_UART_REPL         (1)
Does the C2 have USB?  If not, the comment here is wrong.

2025-07-28 12:00 UTC, dpgeorge commented on ports/esp32/machine_adc.c
> +    #elif CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32C6 || CONFIG_IDF_TARGET_ESP32C2
Why is C6 added here?  There's already a C6 section below.

If the C6 should be here instead, then the one below can be removed.

2025-07-28 12:00 UTC, dpgeorge commented on ports/esp32/main.c
> +    #if CONFIG_IDF_TARGET_ESP32C2 && CONFIG_SOC_XTAL_SUPPORT_26M
Is the `CONFIG_SOC_XTAL_SUPPORT_26M` needed?  It seems like that's unconditionally set on the C2.

Also, maybe this bit can be moved into `MICROPY_BOARD_STARTUP()`?  That would allow a board to not print this newline.

2025-07-28 12:02 UTC, dpgeorge commented
Thanks @projectgus for getting this working, and tweaking the RAM for WiFi/BLE.  That's really good, and this PR is relatively simple.

Just a few minor comments above, but otherwise I think this is good to go in.

2025-07-28 23:45 UTC, projectgus commented on ports/esp32/main.c
> +    #if CONFIG_IDF_TARGET_ESP32C2 && CONFIG_SOC_XTAL_SUPPORT_26M
It's not needed at the moment, but it is possible for a C2-based board to be configured for 40MHz crystal in which case it won't need this workaround.

Putting it in `MICROPY_BOARD_STARTUP()` seems like a good place.

2025-07-29 00:01 UTC, dpgeorge commented on ports/esp32/main.c
> +    #if CONFIG_IDF_TARGET_ESP32C2 && CONFIG_SOC_XTAL_SUPPORT_26M
Isn't there a difference between supporting 26MHz and selecting 26MHz?

Eg, it looks like both `CONFIG_SOC_XTAL_SUPPORT_26M` and `CONFIG_SOC_XTAL_SUPPORT_40M` are currently enabled on the C2.

2025-07-29 00:04 UTC, projectgus commented on ports/esp32/machine_adc.c
> +    #elif CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32C6 || CONFIG_IDF_TARGET_ESP32C2
Good catch, this whole section needed changing (the C2 has one fewer ADC pin than the C3, the C6 has many more than either of the other two).

2025-07-29 00:05 UTC, projectgus commented
@dpgeorge Thanks for the detailed review, have updated!

2025-07-29 00:08 UTC, projectgus commented on ports/esp32/main.c
> +    #if CONFIG_IDF_TARGET_ESP32C2 && CONFIG_SOC_XTAL_SUPPORT_26M
Oh you're right, I picked the wrong config flag! My mistake.

The new version of the PR scopes it to the board so I've removed any `#if` for now.

2025-07-29 00:22 UTC, projectgus commented
With these RAM tweaks there's almost as much free RAM on the C2 as the original ESP32 (without SPIRAM) - 142KiB vs 125KiB:

Original:
```
>>> micropython.mem_info()
stack: 704 out of 15360
GC: total: 56000, used: 3200, free: 52800, max new split: 90112
 No. of 1-blocks: 59, 2-blocks: 10, max blk sz: 19, max free sz: 3287
```

C2:
```
>>> import micropython
>>> micropython.mem_info()
stack: 500 out of 15360
GC: total: 35968, used: 1232, free: 34736, max new split: 92160
 No. of 1-blocks: 22, 2-blocks: 7, max blk sz: 19, max free sz: 2158

2025-07-29 03:22 UTC, dpgeorge reviewed
A few more minor comments.

2025-07-29 03:22 UTC, dpgeorge commented on ports/esp32/boards/ESP32_GENERIC_C2/board_init.c
> + * Development of the code in this file was sponsored by Microbric Pty Ltd
This line does not need to be here.

2025-07-29 03:22 UTC, dpgeorge commented on ports/esp32/boards/ESP32_GENERIC_C2/board_init.c
> +#include "mpconfigport.h"
Should include `py/mpconfig.h` instead.

2025-07-29 03:22 UTC, dpgeorge commented on ports/esp32/machine_bitstream.c
> +    #endif
I'm probably being too picky here, so feel free to ignore this suggestion, but this could be a little cleaner as:
```c
    #if SOC_RMT_SUPPORTED
    if (esp32_rmt_bitstream_channel_id >= 0) {
        machine_bitstream_high_low_rmt(pin, timing_ns, buf, len, esp32_rmt_bitstream_channel_id);
        return;
    }
    #endif
    machine_bitstream_high_low_bitbang(pin, timing_ns, buf, len);
}
```

2025-07-29 03:22 UTC, dpgeorge commented on ports/esp32/boards/ESP32_GENERIC_C2/board.md
> +ESP32-C2-based boards with 4MiB of flash and 26MHz crystal frequency.
Maybe worth saying "with at least 4MiB of flash"?

2025-07-30 00:46 UTC, projectgus commented on ports/esp32/boards/ESP32_GENERIC_C2/board_init.c
> + * Development of the code in this file was sponsored by Microbric Pty Ltd
Oops, copied wrong boilerplate!

2025-07-30 00:50 UTC, projectgus commented on ports/esp32/boards/ESP32_GENERIC_C2/board.md
> +ESP32-C2-based boards with 4MiB of flash and 26MHz crystal frequency.
I changed this because currently all ESP8684 chips have either 2MB or 4MB of embedded flash, and I actually thought the flash controller only supports those sizes. But it looks like it can at least theoretically support more.

2025-07-30 00:52 UTC, projectgus commented
@dpgeorge Updated!

2025-07-30 01:14 UTC, dpgeorge approved these changes
Looks good now, thanks!

2025-07-30 01:15 UTC, merged