Some improvement in esp32 readme.
micropython/micropython pull request #16468
Opened 2024-12-22 05:49 UTC by garywill

### Summary

1. To add user to Linux `dialout` group, `usermod` is the universal Linux way. `adduser` is Debian-based way.
2. When installing IDF, we don't have to install all toolchains for all chips.
3. List currently MPY supported chip models.
4. Use `network.STA_IF` instead of `network.WLAN.IF_STA`
5. Other typo and gramma corrections

2025-01-17 04:44 UTC, projectgus requested changes
This is good, thanks @garywill for taking the time to submit these improvements!

I have one small request for a change, but otherwise looks good to me.

I think probably we should merge the "Getting a Python prompt on the device" and "Configuring WiFi" steps into the main tutorial documentation and link to there from here, instead of maintaining two near-identical sections of doc. However that can be left for someone to do in the future, doesn't have to be done here unless you're feeling very keen (as the ESP32 tutorial currently redirects into the esp8266 tutorial at about this point.)

2025-01-17 04:44 UTC, projectgus commented on ports/esp32/README.md
> +    wlan = network.WLAN(network.STA_IF)
`network.WLAN.IF_STA` is actually preferred here, the top-level namespace constants like `network.STA_IF` are deprecated and will be removed at some point in the future. (This one was only changed recently in 285e1d0b)

2025-01-17 13:40 UTC, garywill commented on ports/esp32/README.md
> +    wlan = network.WLAN(network.STA_IF)
Corrected in newly commit

2025-01-28 01:13 UTC, projectgus approved these changes

2025-02-28 05:19 UTC, merged