Extend audio playback documentation
micropython/micropython pull request #3222
Opened 2017-07-19 08:00 UTC by riklaunim

Also the http://micropython.org/resources/examples/wave.py file imports:

```
from _collections import namedtuple
```

which isn't compatible with latest pyboard micropython firmware. Should be without the "_"

2017-07-19 08:44 UTC, pfalcon requested changes
Besides inline comments, please follow commit message conventions: https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md

2017-07-19 08:44 UTC, pfalcon commented on docs/pyboard/tutorial/amp_skin.rst
> +Or by using online converters like http://audio.online-convert.com/convert-to-wav
-1. Sites like this come and go, no need to collect broken links in the docs. (Feel free to argue on this one.)

2017-07-19 08:44 UTC, pfalcon commented on docs/pyboard/tutorial/amp_skin.rst
> +This should play the WAV file. Note that this will read the whole file into RAM so it has to be small enough to fit in it.
Please wrap lines to 70 chars.

2017-07-21 06:53 UTC, dpgeorge commented
Thanks!  Squashed and merged in 8c9e22c12740477035bd5d78e43beeb6df598588 with minor changes to the text to make it read a bit better.

> from _collections import namedtuple
> 
> which isn't compatible with latest pyboard micropython firmware. Should be without the "_"

Thanks for the pointer, this is now fixed.

2017-07-21 06:53 UTC, closed without merging