Compile-time MICROPY_DEBUG_VERBOSE-flag
micropython/micropython pull request #3236
Opened 2017-07-24 17:00 UTC by naums

Added a compile-time flag usable in `mpconfigport.h` for making the interpreter extremely talkative. When MICROPY_DEBUG_VERBOSE is set to 1 the interpreter will actually execute every DEBUG_printf-statement inside it's code, therefore print loads of information, like garbage-collector calls. This makes debugging a new port a bit easier.

2017-08-02 09:01 UTC, pfalcon requested changes
Please follow https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md

2017-08-02 10:12 UTC, naums commented
I only see the commit-message as non-conformant to the code-conventions, right? If that is the only thing preventing a merge, then please close the pull-request unmerged.

2017-08-02 10:47 UTC, stinos commented
>  If that is the only thing preventing a merge, then please close the pull-request unmerged

Can't you just change the commit message, amend, push --force so we can get this merged?

Also the addition to py/mpconfig.h has an abdundance of spaces

2017-08-02 20:40 UTC, naums commented
done.

2017-08-13 19:26 UTC, pfalcon commented
Thanks for updating the commit message. What about this comment from @stinos:

> Also the addition to py/mpconfig.h has an abdundance of spaces

?

2017-08-15 01:55 UTC, dpgeorge commented
Thanks @naums for updating the PR.  I fixed the spaces in py/mpconfig.h and reworded the comment slightly for that new option.  Merged in ace9fb54053c29574bdf81ffacc5ddcf9d4b45d9

2017-08-15 01:55 UTC, closed without merging