esp8266: Allow disable of REPL on UART0
micropython/micropython pull request #3277
Opened 2017-08-16 11:06 UTC by dmkent

This PR builds on the great initial work of @mhoffma in #2891. It rebases that work then extends those changes to address comments on #2891 by @dpgeorge, provide ability to enable/disable REPL and further decouple esp_mphal.c, machine_uart.c and uart.c from one-another 

It pumps all UART RX into it's own ring buffer as well as conditionally to the main REPL input_buf. TX will go out on the UART as normal but this adds a conditional TX API for esp_mphal to use that will conditionally disable REPL TX to UART.

The conditional RX/TX behaviour is currently switched using an extra parameter to UART.init(). This would need to change to align with whatever is eventually decided in #3144. This shouldn't be very onerous if the `uos.dupterm(obj, index)` approach is adopted.

To make use of this behaviour the process is basically:

1. Boot ESP8266, connect via UART, use REPL on UART to setup webrepl.
2. Power down, connect whatever other device you want to your UART.
3. Boot and connect to webrepl.
4. Reinitalise the UART to disable REPL (and set other params as needed):

    `uart0.init(use_repl=0, baudrate=9600, rxbuflen=256)`

5. Use the webrepl and the Pythonic UART API to talk to your other device using UART without any weird REPL interaction!

2017-08-18 00:51 UTC, elfmimi commented
This is what I am waiting for. I will try it out.

2017-08-20 19:09 UTC, pfalcon requested changes
As discussed in the previous tickets, UART should be refactored in a separate class, and its usage or not usage for REPL should be achieved using machine.dupterm() (https://github.com/micropython/micropython/pull/3144).

2017-08-28 03:28 UTC, flauzino7 approved these changes

2017-09-17 13:35 UTC, mhoffma commented
Man I was just looking for this, thanks for carrying the torch!

2017-09-22 02:58 UTC, dpgeorge commented
@dmkent thanks for making further progress with this topic.  Now that #3144 merged (uos.dupterm behaviour) would you like to update this PR to use that instead of the `use_repl` argument to the UART constructor?  If not then I will take it from here.

2017-09-22 21:49 UTC, dmkent commented
Sure, happy to look into it.

Couple of things that might be simpler resolved first.

1. Which index should each stream go on? UART=> 1, webrepl => 0 is less breaking (i.e. that would replicated current behaviour) but UART => 0, webrepl => 1 seems more logical given the UART is more or less the default REPL stream.

2. The current UART interface is not all that far from a standard ``write``/``readinto`` interface so will look into making that consistent.

3. Where is the state best maintained? I'm assuming building on the ``term_obj`` in ``py/mpstate.h`` is the line of least resistance but is there another better preference?

2017-09-25 05:51 UTC, dpgeorge commented
> Which index should each stream go on? UART=> 1, webrepl => 0 is less breaking (i.e. that would replicated current behaviour) but UART => 0, webrepl => 1 seems more logical given the UART is more or less the default REPL stream.

The original discussion in #3144 was to leave index=0 free for the user to use, and then index=1 would have the UART in it by default.  So that means the user can do `uos.dupterm(some_serial_object)` and it will "just work", and won't destroy the existing REPL source.

But, looking at it again after some time, it does seem more logical to put the default REPL source at index=0.  Doing it that way is not such a breaking change for esp8266 because WebREPL is the main user of dupterm and the WebREPL setup code must anyway change no matter what approach is taken.  So might be better to aim for this behaviour, of UART at index=0.

> The current UART interface is not all that far from a standard write/readinto interface so will look into making that consistent.

It should already have exactly a readinto/write interface.

> Where is the state best maintained?

The esp8266 is short on RAM so objects should only be created if needed.  Thus the UART should be created on the heap when needed and a pointer to it stored in the root pointers upon creation.

2017-10-12 11:00 UTC, dmkent commented
@dpgeorge, while I'd love to get back to this, it's not likely to happen in the next month or so. Feel free to pick it up if you have the inclination in the mean-time.

2018-01-20 17:07 UTC, ulno commented
It would really be nice if this could somehow be made work in mainline. However doing that patch seems way out of my league as there seem so many changes regarding this fact from 1.9.1 (what this patch is for) to 1.9.3.. I assume nobody is interested to use the serial port on esp8266 upy for anything else than debugging as also all other related threads are dead? Is there any place where a normal human being mediumly skilled in c and c++ but not working 8 hours a day on upy development can start to revive this patch?

2018-04-08 22:32 UTC, roger- commented
Any updates on this?

2018-05-08 06:15 UTC, dpgeorge commented
Sorry, this did get quite stale.  It's not forgotten!

2018-05-15 05:34 UTC, dpgeorge commented
Please see #3784 for my alternative to this PR.

2018-05-21 01:35 UTC, dpgeorge commented
Ability to disable UART(0) on the REPL was implemented in afd0701bf7a9dcb50c5ab46b0ae88b303fec6ed3

2018-05-21 01:35 UTC, closed without merging