Symlinks, modules improvements for WINDOWS
micropython/micropython pull request #3340
Opened 2017-09-30 18:07 UTC by chrismas9

This PR provides a solution for building MicroPython with symlinks under WINDOWS.

As cloned or forked from GitHub MicroPython STM32 port has symlinks to the lcd160cr driver and onewire driver which fail to compile and break the build. This PR, which builds on #3310 allows MicroPython to be built out of the box on Windows with no warnings or errors.

It is particularly aimed at WINDOWS users who just want to add their own frozen modules, without having to debug and learn why build fails. It allows Python programmers to freeze modules without having to learn about make or symlinks. I will be writing a tutorial on how to build MicroPython under WINDOWS.

Under WINDOWS a Linux symlinks looks like a text file named after the module and containing one line with the path and module name, eg:

onewire.py contains ../../../drivers/onewire/onewire.py

I have replaced SHELL(FIND and SED) with a python script - tools/find-modules.py - which parses the symlinks, searches for modules in the modules directory and creates a list of path/file.py to compile. Since these files have different source directories it builds a temporary makefile, frozen.mk in the BUILD directory, with a separate rule for each module. It outputs a module list for mpy-tool.

As a result of the way it parses symlinks users can also create fake symlinks (eg under WINDOWS). These are one line files with the path/filename.py link to the module. An extension of this is to search for frozen.lst in the modules directory which can contain multiple lines of links and comments.

Currently all STM32 ports inherit the LCD drivers for the LCD160CR modules. A final addition to the search capability is to handle multiple modules directories, eg one each for the port, board and project. This would permit onewire.py to be included with all boards (in stm32/modules), lcd160cr.py to be included only with pyboards (in PYBV10/modules, etc) and user modules to be added in stm32/projects/modules.

I have included a set of module directories and test files in a second commit which I will remove and squash after testing.

To test all the features run:

make FROZEN_MPY_DIR="modules projects/modules3"

Note that the quotes are required if there is more than one module.

This has been tested for clean and incremental builds on:
Cygwin and Python 3.6
Windows 10 Bash (WSL) and Python 2.7
ChaletOS with Python 2.7. ChaletOS is Debian based with a Windows style shell. Run under VMWARE.

As far as I can tell this has no impact on Linux users, but makes life much easier for Windows users. Linux users can also take advantage of modules.lst and multiple module directories.

The changes to building and using mpy-cross.exe under WINDOWS are discussed in #3310 

find-modules.py is based in part on tools/make-frozen.py which has no copyright or license. The rest is my original work and MIT licensed.

2017-09-30 18:48 UTC, chrismas9 commented
I will try to debug Travis failure in unix/extra_coverage.py tomorrow.

2017-10-03 12:03 UTC, chrismas9 commented
If considered useful I can add the same parsing to make-frozen.py. Is anyone likely to use symlinks with FROZEN_DIR?

2017-10-03 12:33 UTC, pfalcon commented
On a POSIX system (and there's no other standard for open operating systems), one can use symlinks anywhere.

2017-10-03 12:55 UTC, chrismas9 commented
Yes, I understand that, and learning Linux is fine for serious users. 

But there is a large population of casual Python programmers and students using Windows every day who only need to build MicroPython so they can add frozen modules or change configuration including people stepping up from micro:bit to pyboard. At the moment they can't build MicroPython because of the symlinks for lcd160cr.py and onewire.py. Also if you are targeting small memory devices (256k, 384k) you don't want those modules in the STM32 port, they are better in the PYBxxx builds only, which is why I want to support multiple module directories.

It's really only directories using symlinks in the MicroPython releases that need this support.

2017-10-03 13:06 UTC, stinos commented
Since Windows on an NTFS drive has symbolic links which are readably by cygwin (and probably msys as well) maybe an easier option is to convert the symlinks to Windows symlinks? Wouldn't be surprised if such a utility exists already. Or maybe git has already an option to do such thing?

2017-10-03 13:26 UTC, chrismas9 commented
I looked into Windows symlinks and the general consensus is that its difficult. There are also problems running VM's including WSL. Microsoft and Ubuntu haven't released a solution for WSL yet. Windows symlinks don't work over networks either.

My solution should allow MicroPython to just download and build anywhere.

2017-10-03 18:08 UTC, stinos commented
> Windows symlinks don't work over networks either

It's not as simple as that, I'm looking at a working one right now, so I assume this means there can be cases where it does not function. Likewise for the WSL issue: symlinks in Bash on Windows itself are ok. Though you likely can't have symlinks in Windows pointing to something in WSL or so. So yes it's difficult to handle everything anywhere but the subset of cases where it does work seems pretty large.

2017-10-03 18:52 UTC, virtualguy commented
+1 for making Windows builds easier. Git (for Windows) support for symlinks is getting better but its not 100% fool proof. Having another script that complicates the build process isn't ideal but it does provide the flexibility for frozen which I have been doing manually.

2017-10-03 18:54 UTC, pfalcon commented
The patch looks somewhat complicated. There're multiple typos and PEP8 inconsistencies.

2017-10-03 18:55 UTC, pfalcon commented
Also, as far as I can tell, it duplicates functionality already provided by existing tool, `tool/mpy_cross_all.py`.

2017-10-06 04:39 UTC, chrismas9 commented
Rebased and run through PEP8. I have left code lines long since half the programs in tools have line lengths of about 130. It's not clear what the MicroPython line length policy is. Do I work by example or strict PEP8?

The main purpose of this patch is to make MicroPython compile out of the box on any platform and allow users to add their own project modules easily without delving into or modifying MicroPython. There are two part to achieving this.

1. Process the existing symlinks in the distribution under Windows.
2. Allow users to specify another modules directory in their own project repository without finding and pointing to the built in modules.

The idea is that a Python programmer with no C or Makefile experience just clones MicroPython and runs:

`make BOARD=PYBV10 FROZEN_MPY_DIR="modules my_project_modules"`

`tool/mpy_cross_all.py` doesn't achieve any of this. It just builds from one module tree.

I terms of complexity one could argue that the whole makefile system is complex, but makes building and configuring MicroPython easier for users. That is my goal with this - simplicity for users.

2017-10-07 07:26 UTC, pfalcon commented
> I have left code lines long since half the programs in tools have line lengths of about 130. It's not clear what the MicroPython line length policy is. Do I work by example or strict PEP8?

By example (universal rule which works in many cases and with any project). We don't follow unreasonable PEP8 requirements, like using arbitrary line length rooted in last-century constraints (and that's about the only exception).

2017-10-07 07:53 UTC, pfalcon requested changes
> The main purpose of this patch is to make MicroPython compile out of the box on any platform and allow users to add their own project modules easily without delving into or modifying MicroPython.

That's not what the title says, it says something pretty different. It says that you want to "improve" symlink, module handling just for "WINDOWS". Looking inside, it's pretty big code drop which affects all the ports. Please don't be surprised if your patch is judged based on the title you gave it (and an apparent case that you miss that it affects all ports, instead advertising it as just for "WINDOWS").

> The main purpose of this patch is ... 1. ... 2. ...

> tool/mpy_cross_all.py doesn't achieve any of this. It just builds from one module tree.

Yeah, and that the problem of this patch - mpy_cross_all.py is intended to be a tool to do all things which mpy-cross itself can't do. But it starts simple, and intended to grow gradually based on usecases. You ignore it and proceed with a patch which tries to do bunch of things at once, leading to a large code drop, affecting building in god knows which way(s).

Instead, please try to do it step by step, reusing and sustainably extending the existing toolset. What's the first problem you want to solve? Desire to workaround symlinks handling on Windows? That's it:

1. Integrate mpy_cross_all.py into the build process. If any issue arise, discuss before switching to other ways of doing it.
2. Add adhoc symlink parsing to mpy_cross_all.py.

These should be separate commits, relatively simple (== easy == fast) changes for review, and as much as should fit in the first pull request. Other changes should go in separate pull requests to ease the review likewise (should be trivial).

> That is my goal with this - simplicity for users.

That's definitely a good intention, but not at the expense of the complexity and maintainability of MicroPython itself please.


This is the request to rework this patch.

2017-10-07 09:51 UTC, chrismas9 commented
@pfalcon Thanks for your guidance. What I will do is:

1. Use `tools/mpy_cross_all.py` to compile modules.

2017-10-07 12:03 UTC, chrismas9 commented
@pfalcon Thanks for your guidance. What I will do is:

1. Submit PR to make `tools/mpy_cross_all.py` use mpy-cross.exe under Windows as per #3310 
2. Use `tools/mpy_cross_all.py` to compile modules.
3. Verify that the same parameters are sent to `mpy-cross`. Test under STM32 and unix coverage.
4. Add symlink parsing to `mpy_cross_all.py`.
5. Test locally.
6. Submit for review.


One consequence of this is that all modules will be unconditionally compiled, whereas make does incremental compiling. Is this a problem?

Later, if accepted:

Submit a PR to add symlink parsing to `tools/make-frozen.py`
Submit a PR to handle multiple module directories, eg port, board and project.
Submit a PR to move `lcd160cr` to the PYBxxx boards only to reduce size of other builds.

Are you happy with this approach?

2017-10-07 12:24 UTC, pfalcon commented
> One consequence of this is that all modules will be unconditionally compiled, whereas make does incremental compiling. Is this a problem?

Yes, that's something to discuss right away. Why did you go that way of generating a makefile which then needs to be included, etc. That's quite a complex way and including generated makefiles has its issues on its own. I don't believe we do that anywhere in the build system. Whereas Zephyr port has to resort to doing that, and I wish it didn't. How flexible is your solution? What happens if a new file, directory added to set of modules to frozen? What happens if file/dir deleted?

Make has its limits on flexibility, and I don't believe you covered all cases. Feel free to correct me. However, my answer to all the questions above is: yes, it's better to just quickly run mpy-cross on few files than invent complex schemes which still won't work for all cases.

We however want to build things once, and make to be idempotent, i.e. once it has run, further runs should finish ASAP (ideally, don't do anything at all).

2017-10-07 12:27 UTC, pfalcon commented
> Submit PR to make tools/mpy_cross_all.py use mpy-cross.exe under Windows as per #3310

Yeah, I'd suggest to just add an option to take full path of mpy_cross, that's how it would integrate with existing Makefile.

2017-10-07 12:34 UTC, pfalcon commented
> Are you happy with this approach?

Roughly, yes, but the whole idea of doing is step by step is to not try to embrace all at once, and let the previous guide the next one.

2017-10-07 12:35 UTC, pfalcon commented
And thanks for giving it a try (an alternative solution).

2017-10-07 13:28 UTC, chrismas9 commented
> Why did you go that way of generating a makefile which then needs to be included, etc. That's quite a complex way 

Because I wanted to replicate the existing behaviour of incremental compiling and I couldn't figure out any other way to do it with a single rule with multiple source directories. I only want to add extensions without breaking current behaviour for those that are happy with current behaviour. And I'm learning to program again and sometimes I will do silly things.

> How flexible is your solution? What happens if a new file, directory added to set of modules to frozen? What happens if file/dir deleted?

I created lots of temporary modules and directories to test that and I only create a make rule for files that are found through `os.walk`. But I didn't think to check if a link pointed to a valid .py file, so that would fail if there was a link, but no file. But I am happy to use `mpy-cross-all` and always compile if you prefer.

> We however want to build things once ...

I guess that's the tradeoff of not using make, unless I add the dependency checks in `mpy-cross-all`.

> And thanks for giving it a try (an alternative solution).

I want to be a useful contributor, so I need to learn to do it right. I will probably keep making mistakes, but I'll try not to make the same mistake twice. I'm also going to build more test scripts instead of relying on Travis CI after submitting a PR. Is there a way to run the Travis tests on my dev branch?

2018-09-04 04:28 UTC, andrewleech commented
Windows git support for symlinks is sufficient for micropython now, at least on Win 10. I haven't tested on older windows but I don't think it's specific to 10.

I'm building micropython quite successfully on windows, using the WSL bash for actually running make, gcc, etc. https://docs.microsoft.com/en-us/windows/wsl/install-win10

The symlink support in git-for-windows isn't enabled by default however, it does need to be explicitly enabled:

When installing git-for-windows the wizard gives an option to "Enable symbolic links": 
![](https://i.stack.imgur.com/rQF1w.png)
https://stackoverflow.com/a/42137273

and/or it can be enabled when initially cloning the repo: 
`git clone -c core.symlinks=true --recursive https://github.com/micropython/micropython.git`

This does require a specific extra "Create symbolic links" privilege when cloning, you can either
* clone from Administrator cmd prompt
* On windows 10, enable "developer mode": https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development
* Enable just the specific priv: https://github.com/git-for-windows/git/wiki/Symbolic-Links#allowing-non-administrators-to-create-symbolic-links

2019-12-08 10:42 UTC, closed without merging

2019-12-09 02:07 UTC, dpgeorge commented
For the record, all symlinks have now been removed from this repository (but not necessarily submodules), see eg ce1de1faf082abfcc5469ad3d70b88aaa0060ec3, b1c0355b9359b0a63e08d9e5f33755f5919a6b8e, e814db592dfa574a4f41717a1bc1734919a780c4, a8138b75b1d3ca8af01e4ad717c6cdb3f733c61d