extmod/modussl_mbedtls.c: Added finaliser
micropython/micropython pull request #3390
Opened 2017-10-27 04:20 UTC by MrSurly

Per https://github.com/micropython/micropython-esp32/issues/209#issuecomment-339855157

2017-10-27 04:22 UTC, MrSurly commented
If accepted, please propagate to ESP32.

2017-10-27 05:12 UTC, dpgeorge commented
A problem that this brings up is that the GC is not reentrant.  That means a finaliser cannot explicitly free memory on the uPy heap.  In the best case a call to gc_free() in the finaliser does nothing.  In the worst case (eg with threading enabled) it leads to deadlocks.  That hasn't been an issue in the past because all uses of finalisers are to close files/sockets, not to free memory on the uPy heap (which is anyway done automatically).

The concern then is that for ports that use the uPy heap for allocating mbedtls objects (which is not the case for esp32 which has a separate heap), this patch will lead to bugs.

2017-10-27 07:25 UTC, pfalcon requested changes
Please add to the commit message a detailed description why the change is made and what it brings. (This generally applies to all commits.)

2017-10-27 18:53 UTC, MrSurly commented
@pfalcon Amended commit message

2017-10-27 18:53 UTC, MrSurly commented
@dpgeorge Added a guard `#ifdef` around finaliser.

2017-10-27 20:42 UTC, pfalcon approved these changes
Thanks.

2017-10-27 20:43 UTC, pfalcon commented
Two commits can be squashed into one btw.

2017-10-28 10:09 UTC, pfalcon requested changes
Oh, btw, all options added should be listed in py/mpconfig.h, or we would have lost track of them long ago.

2017-10-28 16:18 UTC, MrSurly commented
@pfalcon 
* Updated py/mpconfig.h
* Generalized the define to `MICROPY_PY_USSL_FINALISER`
* Added this define, with a comment to `py/mpconfig.h`
* Squashed into one commit

2017-10-29 14:01 UTC, pfalcon commented on py/mpconfig.h
> +// Whether to add finaliser code to uSSL
Better to say "Whether to add finaliser to ussl objects".

2017-10-29 14:02 UTC, pfalcon approved these changes
Looks good, thanks. Minor documenting comment suggestion.

2017-10-30 04:28 UTC, dpgeorge commented
Merged in 74ec52d85758ad9da7a3abb24257511b22d74964

2017-10-30 04:28 UTC, closed without merging