unix/moduselect: Raise KeyError in poll.unregister() and poll.modify().
micropython/micropython pull request #3402
Opened 2017-10-31 01:50 UTC by reidwagner

If a user attempts to unregister or modify the eventmask of an object not already registered with the poll object, raise a KeyError.

2017-10-31 08:00 UTC, pfalcon requested changes
-1. I found the current behavior to be the desired behavior for a typical I/O scheduled application (exemplified by uasyncio). So, please describe your usecase of wanting to spend more memory on allocating exceptions and more code on handling them (how?), and to burden everyone else with the same.

2017-11-02 22:36 UTC, pfalcon commented
As a compromise proposal, I may suggest e.g. returning -1 from these methods, and throw exceptions in Python wrapper.

2017-11-03 03:26 UTC, reidwagner commented
Thanks for the quick feedback. Sorry I haven't been able follow up this week. I made this change to address the TODO items, not with a specific use-case in mind, and for CPython compatibility. I would defer judgment of whether this functionality is "worth it" to you or the original author.

That said, I realize there is a mistake as modify raises an OSError instead of KeyError as the TODO comment states. I did test unregister in CPython but I guess modify slipped by.

Returning -1 to a wrapper I could look into if you think that would be useful and non-disruptive.

2017-11-03 22:01 UTC, pfalcon commented
> I made this change to address the TODO items

Yeah, I figured that might be the case, thanks for confirming that. Well, something would could lead to doubts is "If it's so easy and obvious, why if it wasn't done already." That may be overlook, but it's good idea to think there might be a reason behind it. Not every "TODO" requires a "fix". Yeah, we'll need to do something about them - eventually, and that might be just removing them.

Another good principle to follow "if it ain't broke, don't fix it". https://github.com/micropython/micropython/wiki/ContributorGuidelines suggests to have a usecase behind each change, especially if it adds code, not removes it.

At the same time, we do have a list of things which are deemed useful, for attention of folks who'd like to contribute something useful: https://github.com/micropython/micropython/issues/1331. (And there're no lack of other RFCs and things to test, which could extra pair of eyes/hands very well.)

Thanks.

2017-11-05 17:09 UTC, reidwagner commented
Great, thanks for the links. Because someone else wrote TODO in a comment probably isn't a good excuse for breaking the use-case policy.

Because I don't have a strong argument for this change I'm going to close this PR and perhaps it can be referenced in the future if an issue is opened for unregister and modify to raise exceptions.

2017-11-05 17:09 UTC, closed without merging

2017-11-05 17:29 UTC, pfalcon commented
Sounds good. Btw, I just pushed another commit which relies on the current behavior: https://github.com/micropython/micropython-lib/commit/f81285ff4e37c0a06e2c5f6fe9893d814bacc7db