modwebsocket: Add client support
micropython/micropython pull request #3406
Opened 2017-11-02 05:47 UTC by ccooper21

This change adds websocket client support as per RFC6455.  Section 5.1 states
that a websocket client must mask all frames that it sends to the server.
Further, section 5.3 states the masking key is a 32-bit value chosen at random
by the client unique to each frame.  These requirements are now implemented.
A non-compliant debug mask is also supported, allowing control of the masking
key.

2017-11-02 19:48 UTC, pfalcon commented
Thanks for this contribution! What's interesting and that I lately also was thinking how to "finish" this module and in particular add client support. But I thought also about other things, and it makes it not so easy... Let me however start with pointing few immediate problems with this patch as it is.

2017-11-02 20:00 UTC, pfalcon requested changes

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +        { MP_QSTR_sock, MP_ARG_REQUIRED | MP_ARG_OBJ, {.u_obj = MP_OBJ_NULL} },
This should be empty qstr.

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +        { MP_QSTR_use_blocking_writes, MP_ARG_BOOL, {.u_bool = false} },
We always save for the space, so using such long arg names is no-no.

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +        { MP_QSTR_is_client, MP_ARG_BOOL, {.u_bool = false} },
This should use the same terminology as "ssl" module.

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +        { MP_QSTR_debug_mask, MP_ARG_KW_ONLY | MP_ARG_OBJ, {.u_obj = MP_OBJ_NULL} },
I'm always for having debugging/diagnostic facilities in the code, but they should be properly #ifdef'ed and off by default.

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +    o->do_write_masking = !arg_vals.is_client.u_bool ? NO_WRITE_MASKING : NORMAL_WRITE_MASKING;
At least remove "!" and swap args. I'd also use normal "if" here.

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +            // a platform specific resource include reading an ESP8266's
I'm all for detailed comments, but specifics of a particular chip in a generic module are superfluous.

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +            // cryptographically motivated.  The "urandom" module should be
I'd remove such a statement, it's subjective.

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +            mp_load_method(mp_module_get(MP_QSTR_urandom), MP_QSTR_getrandbits, dest);
The code to get a random value should be factored out to a function.

2017-11-02 20:00 UTC, pfalcon commented on extmod/modwebsocket.c
> +            byte masked_buf[size];
Really? But size can be 1GB.

2017-11-02 20:02 UTC, pfalcon commented
Besides the above the bigger conceptual problem is how to support non-blocking write mode for such stream wrappers: https://github.com/micropython/micropython/issues/3396 . I invite to think how the code you add can be made useful for async non-blocking writers. (If you don't have ideas/not interested, I can share some of my ideas.)

2017-11-03 19:53 UTC, pfalcon commented
Async implementation of websockets which needs client support: https://github.com/micropython/micropython-lib/pull/228

2017-11-05 18:28 UTC, ccooper21 commented
@pfalcon Thanks for the quick review, feedback, and encouragement!  I hope to get this wrapped up in short order and move on to further tasks.  To provide context, I'm working on integrating with the AWS IoT MQTT-based service via websockets on an ESP8266.  I have this working on the UNIX port, but need to do further work for the ESP8266 port due to the MCU's constraints.  Ultimately this will require submitting more pull requests, and likely revisiting some stagnant pull requests from others.  

I think I am aware of the considerations related to writing code for an embedded environment, but I am finding translating this into specific decisions to be more challenging.  Most of my experience is related to enterprise software, which has a completely different set of considerations.  I will likely have some questions regarding your feedback shortly.  Thanks for your guidance as I proceed!

2021-05-04 05:25 UTC, dpgeorge commented
Closing due to inactivity (specifically, the feedback has not been addressed).

This would be a great feature, so feel free to reopen against latest master.  Things to consider would be how to make it work with uasyncio (ie non-blocking).

2021-05-04 05:25 UTC, closed without merging