Ssd1306 improvements
micropython/micropython pull request #3411
Opened 2017-11-03 21:17 UTC by zgyarmati

This patchset improves the support for the SSD1306 displays: the previous version used I2C ops available only on ESP8266, and as some of the I2C display modules have reset pin (but apparently not all of them), we also add optional support for it here. Finally now there is a test/demo script with some comments about wiring to show example about the usage of the driver.

2017-11-29 20:21 UTC, SpotlightKid requested changes
The commit message should be amended according to https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md#git-commit-conventions

2017-11-29 20:21 UTC, SpotlightKid commented on drivers/display/ssd1306_test.py
> +    """
Shouldn't we better give the wiring for the Pyboard V1.1 here?

Also, some formatting improvements:

```
def test_spi():
    """Test SDD1306 module attached via SPI.

    Wiring for Pyboard, SPI bus #1:

    | SDD1306 | Pyboard | Function     |
    | ------- | ------- | ------------ |
    | DC      | ??      | data/command | 
    ....
```

2017-11-29 20:21 UTC, SpotlightKid commented on drivers/display/ssd1306_test.py
> +    """
Same as above.

2017-12-03 17:01 UTC, zgyarmati commented
Thx for the detailed review! Fixes will follow.
 Unfortunately i don't own a Pyboard, so i would need someone to hook it up and confirming the setup before adding the Pyboard wiring.

2017-12-03 17:14 UTC, SpotlightKid commented
I'll try to do that later tonight.

2017-12-04 18:34 UTC, SpotlightKid commented
> I'll try to do that later tonight.

I'm sorry, but it seems that my only ssd1306 module with an SPI interface is broken, so I can't test the `test_ssd1306.py` module properly. I tested it successfully with an ssd1306 module with an I2c only interface (4 pins), though.

Since the mapping of Pyboard pin names to MCU pin names [is well-known}(http://micropython.org/resources/pybv10-pinout.jpg), we can specify the wiring for the Pyboard with confidence nevertheless. I propose these docstrings for the `test_spi` and `test_i2c` functions. I've put the table rows in the order of the pins as they appear on the module header, from left to right, looking at the front of the module. Feel free to adapt the pins used for Reset, DC and CS:

(ReST table formatting done with https://ozh.github.io/ascii-tables/)

```
def test_spi():
    """Test SDD1306 display attached via SPI.

    Wiring for STM32F4DISCOVERY, SPI bus #1 (MCU pin names in parentheses):

     ========= ========== ======================
      SDD1306   Pyboard            Note
     ========= ========== ======================
      GND       GND
      VCC       3V3        5V can be used too
      D0        X6 (PA5)   SPI SCK
      D1        X8 (PA7)   SPI MOSI
      RES       X3 (PA2)   Reset
      DC        X4 (PA3)   Data / Command
      CS        X5 (PA4)   SPI SS / Chip select
     ========= ========== ======================

    """
```

```
def test_i2c():
    """Test SDD1306 display attached via I2C.

    Wiring for Pyboard V1.1, I2C bus #1 (MCU pin names in parentheses):

     ========= =========== =========================================
      SSD1306    Pyboard                     Note
     ========= =========== =========================================
      GND       GND
      VCC       3V3         5V can be used too
      D0        X9 (PB6)    I2C SCL (note 1)
      D1        X10 (PB7)   I2C SDA (note 1)
      RES       X11 (PB8)   Reset (optional)
      DC        GND         addr: 0x3C, if set to VCC, addr is 0x3D
      CS        GND         Unused on most displays
     ========= =========== =========================================

    For SSD1306 modules with I2C interface only:

     ========= =========== ====================
      SSD1306    Pyboard           Note
     ========= =========== ====================
      GND       GND
      VDD       3V3         5V can be used too
      SCK       X9 (PB6)    I2C SCL (note 1)
      SDA       X10 (PB7)   I2C SDA (note 1)
     ========= =========== ====================

    note 1) Add a 4.7k - 10k pull-up resistor between pin and VCC.

    """"
```

2017-12-04 18:38 UTC, SpotlightKid commented on drivers/display/ssd1306_test.py
> +    display.hline(0,18,128,1)
There seems to be an off-by-one error here. I think the coordinates are inclusive, i.e. it should be `display.hline(0, 18, 127, 1)` or `display.hline(0,18, width - 1,1)`.

2018-01-19 07:57 UTC, mcauser commented on drivers/display/ssd1306.py
> +            # not all of the modules have reset pin broke out
"Some ~SDD1306~ SSD1306..."

2021-05-11 04:37 UTC, dpgeorge commented
Closing due to inactivity.  Also, a lot of the points here (eg ability to use hardware or software I2C bus) have been fixed now.

2021-05-11 04:37 UTC, closed without merging