extmod/moduhashlib: Add members to `sha256` to make it usable by the `hmac` module.
micropython/micropython pull request #4539
Opened 2019-02-21 22:35 UTC by Jongy

`micropython-hmac` reuiqres extra attributes currently not implemented by `uhashlib`;
This patch enables them (and fixes #4500) if demanded (only for SHA256 though).

2019-02-22 04:39 UTC, pfalcon requested changes
-1 to the whole logic. If some "micropython-hmac" needs extra members, then it should be fixed, not uhashlib.

2019-02-23 22:03 UTC, Jongy commented
> -1 to the whole logic. If some "micropython-hmac" needs extra members, then it should be fixed, not uhashlib.

Fair enough. However, this is basically done to enable the same functionality as done in #4488, and at least the `copy` method has to be implemented in C, while the 2 constants indeed don't have to (or we can just get rid of them.

2019-02-24 05:43 UTC, pfalcon commented
> However, this is basically done to enable the same functionality as done in #4488

That's why you don't see me praising it. And the issue is not a specific change, but meta-process - people take adding bloat as an indulgence to add even more bloat. Whereas adding anything should be seen as an exception. If a change grows code size, it's by definition bad, and the question is whether it adds order of magnitude more goodness than the bad it inherently brings.

> and at least the `copy` method has to be implemented in C

This assumes that copy() is needed, but you can check e.g. Wikipedia that HMAC has nothing to do with copying a hasher object.

Note that I'm not saying that copy() isn't needed in general - maybe it's needed (configurable and disabled by default), but it's bad, bad change, because it doesn't really enable anything (reasonable and conventional) which wasn't available without it, but turns MicroPython into bloat.

2022-06-24 08:39 UTC, closed without merging

2022-08-08 11:49 UTC, jimmo commented
> The hmac module is still broken, but I don't think this is the right way to fix it. Would be better to rewrite the hmac module to not require `copy().

@Jongy I did this in https://github.com/micropython/micropython-lib/pull/515