ports/mimxrt/boards/MIMXRT1060_EVK: Enabled led class for MIMXRT1060_EVK
micropython/micropython pull request #6117
Opened 2020-06-07 03:44 UTC by yanyao12138

board.

- Enabled led class for MIMXRT1060_EVK.

2020-06-07 05:19 UTC, alphaFred requested changes
Hi, thanks for creating the change. I believe you need to make a small adjustment to the macros for turning the LED on/off, if my understanding of the schematics is correct. 

Best regards
alphaFred

2020-06-07 05:19 UTC, alphaFred commented on ports/mimxrt/boards/MIMXRT1060_EVK/mpconfigboard.h
> +#define MICROPY_HW_LED_ON(pin) (mp_hal_pin_high(pin))
According to my understanding of the schematics the user LED is pulled up to 3.3V supply. To switch it on pin should be pulled low I believe.

2020-06-07 05:19 UTC, alphaFred commented on ports/mimxrt/boards/MIMXRT1060_EVK/mpconfigboard.h
> +#define MICROPY_HW_LED_OFF(pin) (mp_hal_pin_low(pin))
Respectively here. To switch it off, pin should be pulled high.

2020-06-07 08:21 UTC, yanyao12138 commented
> Hi, thanks for creating the change. I believe you need to make a small adjustment to the macros for turning the LED on/off, if my understanding of the schematics is correct.
> 
> Best regards
> alphaFred

Yes, you are right, that's my fault, I have updated the PR.

2020-06-07 08:24 UTC, alphaFred commented
> Yes, you are right, that's my fault, I have updated the PR.

No problem. I made the same mistake with my PR for adding support to 1020EVK 😄.

2020-06-07 08:38 UTC, yanyao12138 commented
> > Yes, you are right, that's my fault, I have updated the PR.
> 
> No problem. I made the same mistake with my PR for adding support to 1020EVK 😄.

Thank you very much! So you are now supporting 1020EVK? If it is OK, can you please share your plan for the support of the mimxrt port. So that we can avoid doing the duplicate work😊.

2020-06-07 09:05 UTC, alphaFred commented
> So you are now supporting 1020EVK?
Well that is the board I have sitting on my desk hence I am eager to add it to the `boards` 😄. 

As you know I started working on the `pin` module. So looking forward to exchanging ideas with you about that. I don’t know if this is easier via an issue, PR or email etc.
Once that is done I would like to work on `SPI` module.

2020-06-09 08:55 UTC, dpgeorge commented
Thanks for this!  Rebased and merged in e0d539f79d4ec020636ba7b043fac08030234112

2020-06-09 08:55 UTC, closed without merging