Escaping * : removed escape \ typo
micropython/micropython pull request #6239
Opened 2020-07-11 09:23 UTC by Zenix27

closes #6209

2020-07-11 15:32 UTC, dlech requested changes
It looks like you have accidentally removed some space characters in a few cases.

2020-07-11 15:32 UTC, dlech commented on docs/library/uos.rst
> +.. function:: mount(fsobj, mount_point,*, readonly)
don't remove space

2020-07-11 15:32 UTC, dlech commented on docs/library/btree.rst
> +.. function:: open(stream,*, flags=0, pagesize=0, cachesize=0, minkeypage=0)
don't remove space

2020-07-11 15:32 UTC, dlech commented on docs/library/lcd160cr.rst
> +.. class:: LCD160CR(connect=None,*, pwr=None, i2c=None, spi=None, i2c_addr=98)
don't remove space

2020-07-11 15:32 UTC, dlech commented on docs/library/machine.Pin.rst
> +.. class:: Pin(id, mode=-1, pull=-1,*, value, drive, alt)
don't remove space

2020-07-11 15:32 UTC, dlech commented on docs/library/machine.Pin.rst
> +.. method:: Pin.init(mode=-1, pull=-1,*, value, drive, alt)
don't remove space

2020-07-11 15:32 UTC, dlech commented on docs/library/machine.Pin.rst
> +.. method:: Pin.irq(handler=None, trigger=(Pin.IRQ_FALLING | Pin.IRQ_RISING),*, priority=1, wake=None, hard=False)
don't remove space

2020-07-11 15:32 UTC, dlech commented on docs/library/machine.SPI.rst
> +.. method:: SPI.init(baudrate=1000000,*, polarity=0, phase=0, bits=8, firstbit=SPI.MSB, sck=None, mosi=None, miso=None, pins=(SCK, MOSI, MISO))
don't remove space

2020-07-11 15:32 UTC, dlech commented on docs/library/machine.Signal.rst
> +           Signal(pin_arguments...,*, invert=False)
don't remove space

2020-07-11 15:32 UTC, dlech commented on docs/library/machine.UART.rst
> +.. method:: UART.init(baudrate=9600, bits=8, parity=None, stop=1,*, ...)
don't remove space

2020-07-11 17:09 UTC, Zenix27 commented
Added Space @dlech @jimmo

2020-08-21 03:40 UTC, dpgeorge commented
Thank you for the contribution!  Rebased, squashed and merged in e76c7466b62c940150cf1b5000e18f60a5efa2e3

2020-08-21 03:40 UTC, closed without merging