extmod/uzlib: Add gzip compression support. (update to #5613)
micropython/micropython pull request #6972
Opened 2021-03-01 07:37 UTC by harbaum

This is a new attempt on https://github.com/micropython/micropython/pull/5613. It addresses all of the comments and additionally fixes a memory leak.

This has been stress tested with a few GB of video data as seen [here](https://www.youtube.com/watch?v=9zsAbTVxjMw).

As a quick test gzip compression can be tested against the already present decompression like so:

```
>>> uzlib.decompress(uzlib.gzip("Hello World!")[10:-8], -15)
compressed from 12 to 14 raw bytes
bytearray(b'Hello World!')
```

2021-07-07 04:24 UTC, andrewleech requested changes

2021-07-07 09:16 UTC, harbaum commented on extmod/uzlib/defl_static.c
> +#define sfree(x) ( free((x)) )
Done and verified that it still works

2021-07-07 09:16 UTC, harbaum commented on extmod/moduzlib.c
> +    free(comp->out.outbuf);     // free internal buffer allocated by compression
Done and verified that it still works

2021-10-06 07:41 UTC, dmazzella commented
progress on this?

2022-01-20 12:33 UTC, harbaum commented
Closing since files have moved and changed and the whole uzlib library needed an update.

New pull request at https://github.com/micropython/micropython/pull/8195

2022-01-20 12:33 UTC, closed without merging