mimxrt: Add the machine.spi() class to machine.
micropython/micropython pull request #7400
Opened 2021-06-15 20:12 UTC by robert-hh

This class supports both Controller (Master) an Peripheral (Slave) mode. In order to support Peripheral mode, two keyword arguments have been added:

mode=SPI.CONTROLLER or SPI.PERIPHERAL or SPI.MASTER or SPI.SLAVE
timeout=xxxx   Timeout to wait for a request. On timeout, an exception is raised

Further options:
drive=n  with n being between 1 and 6 or PIN.POWER_1 to PIN.POWER_6. Since the pins used
        by the SPI are fixed, no Pin settings can be made. Thus the drive option is added allowing
        to control ringing and crosstalk on the connection.
gap=nnnnn  The time between sent data items in a frame given in ns. Default is 2 clock cycles.

With the configured clock frequency the fastest baud rate is 33MHz. For messages longer  16 bytes DMA is used. The class uses the existing frame work with extmod/machine_spi.c. I did not want to create a separate class for that.

There are still two dark spots on the implementation:
- Using DMA the data cache is disabled for the short transfer time. Otherwise data access was not reliable. Other less intrusive methods I tried did not work. Suggestions welcome.
- For short messages (<= 16 bytes) in slave mode, write requests by the master are not detected and served in about 1 of 1000 cases, independent from baud rate and request frequency. DMA transfer is reliable.

2021-06-18 09:02 UTC, robert-hh commented
It seems that the cache is not the big problem. I made a test, how long the transfer set-up take with cache enabled and disabled. Note: The cache is disabled only for the last part of the set-up and the actual transfer. The test consists of writing a dynamically created message 10 time in a tight loop. The results.
```
Loop #   with cache   w/o cache
 1          80µs         80µs
2-10        30µs         70µs
```
The 70µs number has little variation, while the 30µs is an average with variation between 10 and 50 µs. So what you see essentially is the effect of cache. The cache is not big. If the code does not run in a tight loop, it is more likely that there is a cache miss in a call to spi.write(), and therefore there is no difference between the two options.

2021-06-23 09:04 UTC, dpgeorge commented
I did not look at this in detail, but the first thing I'd say (as I mentioned elsewhere) is that slave/peripheral mode does not yet have an API defined, and eventually I think it should be something like `machine.SPIPeripheral` for peripheral mode.  So I would suggest to remove the peripheral support from this PR (of course don't discard the code, it will be useful later!).

2021-06-23 09:27 UTC, robert-hh commented
I can do that, even if it was very helpful for testing, allowing a loop test. I do not favor the idea of having just another spi class. My impression is, that the only thing needed may be a return signal form the transfer call, like it exists for UART or I2C, where it is used for error reporting and telling  the number of bytes transferred.

2021-06-23 10:04 UTC, robert-hh commented
The peripheral mode is removed, including the keyword parameters related to it.

2021-06-24 13:22 UTC, dpgeorge requested changes

2021-06-24 13:22 UTC, dpgeorge commented on extmod/machine_spi.h
> +#endif
these can go

2021-06-24 13:22 UTC, dpgeorge commented on ports/mimxrt/board_init.c
> +void BOARD_ConfigMPU(void);
this is not needed

2021-06-24 13:22 UTC, dpgeorge commented on ports/mimxrt/dma_channel.c
> +int allocate_DMA_channel(void) {
the upper case "DMA" looks out of place, doesn't match other code styling; `allocate_dma_channel` would be better

2021-06-24 13:22 UTC, dpgeorge commented on ports/mimxrt/dma_channel.c
> +void free_DMA_channel(int n) {
similar to above, make lower case "DMA"

2021-06-24 13:22 UTC, dpgeorge commented on ports/mimxrt/machine_spi.c
> +#define DEFAULT_SPI_MODE        (MICROPY_PY_MACHINE_SPI_MASTER)
this line isn't needed anymore

2021-06-24 13:22 UTC, dpgeorge commented on ports/mimxrt/machine_spi.c
> +#define MICROPY_HW_SPI_NUM     (sizeof(spi_index_table) / sizeof(spi_index_table)[0])
you can use `MP_ARRAY_SIZE(spi_index_table)`

2021-06-24 13:22 UTC, dpgeorge commented on ports/mimxrt/machine_spi.c
> +        { MP_QSTR_gap,      MP_ARG_KW_ONLY | MP_ARG_INT, {.u_int = -1} },
this is a new argument, maybe it can be called `gap_ns` to emphasise the units?

2021-06-25 07:15 UTC, robert-hh commented
Thanks for the comments. All changes have been implemented.

2021-06-26 01:57 UTC, dpgeorge approved these changes

2021-06-26 06:35 UTC, robert-hh commented
Thanks for approving. Should I rebase & squash the PR?

2021-06-26 12:28 UTC, dpgeorge commented
> Thanks for approving. Should I rebase & squash the PR?

No need, done during merge.

Merged in f45412793e78cd5013b83b8de5219183eb53eca5

2021-06-26 12:28 UTC, closed without merging