initial draft for manifest file
micropython/micropython pull request #7620
Opened 2021-08-05 04:13 UTC by NitiKaur

2021-08-05 04:44 UTC, mattytrentini commented
See #7601

2021-08-05 04:48 UTC, dpgeorge requested changes

2021-08-05 04:48 UTC, dpgeorge commented on docs/reference/manifest.rst
> +* yasmarang_randbelow : returns an unsigned integer below the given argument
this should not be here

2021-08-05 04:48 UTC, dpgeorge commented on docs/reference/manifest.rst
> +* yasmarang_float : returns a number in the range [0..1) using Yasmarang to
this should net be here

2021-08-05 04:48 UTC, dpgeorge commented on docs/reference/manifest.rst
> +def freeze_mpy(path, script=None, opt=0): Freeze the input (see above), which
remove the "def" keyword

2021-08-05 04:49 UTC, dpgeorge commented
Would be good to include a few examples, eg from `ports/rp2/boards/manifest.py`.

2021-08-05 04:57 UTC, dpgeorge commented
The public functions are:
- `include`
- `freeze`
- `freeze_as_str`
- `freeze_as_mpy`
- `freeze_mpy`

2021-08-05 05:46 UTC, pidou46 commented
Maybe a word to explain what the manifest file actually is, what is the aim, before explain how it works ?
Except if it's explain elsewhere.

2021-10-14 03:04 UTC, dpgeorge commented
Merged in e87b2e8bfa71a09f0fe585fc0127e9fa42b68f19 with layout improvements and an examples section.

2021-10-14 03:04 UTC, closed without merging