py\obj.c: Get 64-bit integer arg.
micropython/micropython pull request #8089
Opened 2021-12-15 20:21 UTC by IhorNehrutsa

Add **int64_t mp_obj_get_ll_int(mp_obj_t arg_in)** function.

It's a pair to the **mp_obj_t mp_obj_new_int_from_ll(long long val)**

It uses in the 
ESP32: New hardware PCNT Counter() and Encoder(). #6639

2021-12-15 20:59 UTC, robert-hh commented
Well, this code fails for each and every port. These lines are wrong:
```
   if (arg == mp_const_false) {
        return 0;
    } else if (arg == mp_const_true) {
        return 1;
```
Should probably be arg_in and not arg.

2021-12-17 11:15 UTC, dpgeorge requested changes
There will need to be coverage tests added to `ports/unix/coverage.c` to get 100% coverage of this new function.

2022-06-30 07:55 UTC, IhorNehrutsa commented on py/obj.c
> +        int len = arg->mpz.len;
Done

2025-11-18 06:08 UTC, dpgeorge commented
`mp_obj_get_ll()` was added in c4a88f2ce7da87d5f635ec25edba481917020fd8 (with coverage tests), so I'll close this PR.

2025-11-18 06:08 UTC, closed without merging