nlr - mips port
micropython/micropython pull request #8154
Opened 2022-01-10 13:23 UTC by janwilleke

Add nlr support for mips architecture

2022-01-27 05:50 UTC, dpgeorge requested changes
Thanks for the contribution!

How did you test this?

2022-01-27 05:50 UTC, dpgeorge commented on py/nlrmips.c
> +#undef nlr_push
Is this undef needed?

2022-01-27 05:50 UTC, dpgeorge commented on py/nlrmips.c
> +#include <stdio.h>
Is this include needed?

2022-01-27 05:50 UTC, dpgeorge commented on py/py.cmake
> +    ${MICROPY_PY_DIR}/nlrmips.c
Please sort in alphabetical order, ie before nlrpowerpc.c

2022-01-27 05:50 UTC, dpgeorge commented on py/py.mk
> +	nlrmips.o \
please sort

2022-01-27 08:22 UTC, janwilleke commented
> 

Thank you your your review, I improved are remarks ;-)

As I include micropython into my pic32mz projekt, the linker was missing setjmp, thus I had to fix this, and as maybe other people are using mips too.... 
So its been tested with qemu (as described in the patch) and on pic32mz real hardware.

2022-01-27 11:39 UTC, dpgeorge commented
> So its been tested with qemu (as described in the patch) and on pic32mz real hardware.

Ok great!  I didn't read the commit message, but now I have and it does explain it well.

And I forgot that CI does run a MIPS build and tests, using the unix port.  So I wonder if that build now picks up this nlr implementation rather than setjmp.  Need to check that somehow.

2022-11-15 06:09 UTC, dpgeorge commented
> And I forgot that CI does run a MIPS build and tests, using the unix port. So I wonder if that build now picks up this nlr implementation rather than setjmp. Need to check that somehow.

I checked this and the CI does use this new nlr code.

2022-11-15 06:13 UTC, dpgeorge commented
Rebased and merged in 043dc4dd0cc4679fca96a2d36f1bf7cf1656606f and 40a3aa709c874f1eb3cabd6d8a393ea8042d976c

2022-11-15 06:13 UTC, closed without merging