docs/library/uasyncio.rst: fix description of ThreadSafeFlag
micropython/micropython pull request #8259
Opened 2022-02-04 04:07 UTC by larsks

When a task waits on a ThreadSafeFlag (and the wait method returns), the
flag is immediately reset. This was not clear in the documentation, which
appeared to copy the description of the wait method from the Event class.

2022-02-04 09:25 UTC, peterhinch requested changes
The first statement is true and should be retained. If the ThreadSafeFlag is set, .wait returns immediately:
```python
import uasyncio as asyncio
tsf = asyncio.ThreadSafeFlag()
tsf.set()

async def foo():
    await asyncio.sleep(1)
    await tsf.wait()
    print('got here')

asyncio.run(foo())
```

2022-02-04 14:32 UTC, larsks commented
Sorry, a little over enthusiastic in my edits.

2022-02-07 05:28 UTC, dpgeorge commented on docs/library/uasyncio.rst
> +    Wait for the flag to be set.  If the event is already set then it returns
I think it makes sense to keep the word `flag` here, to be consistent with the rest of this paragraph.

2022-02-09 05:11 UTC, dpgeorge commented
Thanks for this, merged in 8f6924c9fb061742039554a3b5840f6e92aff7f2

2022-02-09 05:11 UTC, closed without merging