shared/tinyusb: Create for reuse, rp2 only for now.
micropython/micropython pull request #9357
Opened 2022-09-19 14:00 UTC by Molorius

2022-09-21 04:12 UTC, projectgus requested changes
Generally this looks good to me, just a couple of minor things! Sorry to ask you to leave most of your work behind for now, but this is a really good foundation.

There is also a file `shared/runtime/tinyusb_helpers.c` which contains the implementation for `MICROPY_HW_USB_CDC_1200BPS_TOUCH`. It might make sense to rename this to `shared/tinyusb/usbd_cdc_common.c` or something like that, I'm not sure. But feel free to leave that for now.

2022-09-21 04:12 UTC, projectgus commented on ports/rp2/usbd.c
> +    memcpy(buf, id.id, len);
suggest using `sizeof(id.id)` here and for the return value

(there is also a constant `PICO_UNIQUE_BOARD_ID_SIZE_BYTES` which would be fine, but `sizeof(id.id)` seems like the best choice to me as that's the actual field you're copying from.)

2022-10-04 03:06 UTC, projectgus commented
@Molorius I used your commit as the basis for a branch to implement USB device drivers in Python (see linked PR). I also have a separate refactoring commit in that PR - if it's OK with you then I'll submit a new USB refactoring PR with your commit plus that one.

2022-10-28 20:53 UTC, Molorius commented
Hello @projectgus yes it is okay with me. Thanks for asking.

2022-10-31 03:10 UTC, dpgeorge commented
@projectgus how shall we proceed here?  Do you want to submit a separate PR (separate to this and #9497) to do the refactoring?  Otherwise I see it's already part of #9497 and can be reviewed with that set of commits, although that's not my preference because it's easier to review and merge smaller chunks of work.

2022-11-01 22:28 UTC, projectgus commented
@dpgeorge Yes, my plan has been to submit a separate refactor PR. I wanted to wait until hearing back from @Molorius (thanks!), and also until I thought the refactor changes were finalised and I wasn't going to do much more tweaking.

I'm probably are at this point now, so I'll submit a refactoring PR today.

2022-11-11 05:56 UTC, dpgeorge commented
This was merged in eed4eb2645aa3975ef822f4b34110730811690b7 as part of #9816.

Thanks @Molorius for initiating this refactor!

2022-11-11 05:56 UTC, closed without merging